sonar.projectKey=hoangnam-esign_file-storage_9b3da484-4c8d-4cf8-a652-aee552487eda
sonar.projectName=File Storage Service

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.min.js

sonar.sourceEncoding=UTF-8
sonar.javascript.file.suffixes=.js,.jsx
