name: SonarQube

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  sonar:
    uses: hoangnam-esign/devops-templates/.github/workflows/sonar.yml@main
    secrets: inherit
    with:
      language: nodejs
      node-version: "20"
